In [39]:
import torch

x = torch.arange(4.0)
x.requires_grad_(True) 

tensor([0., 1., 2., 3.], requires_grad=True)

In [41]:
x.grad

In [45]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [47]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [49]:
x.grad == 4 * x

tensor([True, True, True, True])

In [51]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad 

tensor([1., 1., 1., 1.])

In [65]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.], grad_fn=<ZeroBackward0>)

In [67]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [69]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])